#!/usr/bin/sh

# env
JAVA_OPTIONS="-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog"

CLASSPATH="./lib/activation.jar"
CLASSPATH="${CLASSPATH}:./lib/agent.jar"
CLASSPATH="${CLASSPATH}:./lib/backport-util-concurrent.jar"
# CLASSPATH="${CLASSPATH}:./lib/cfejb_client.jar"
CLASSPATH="${CLASSPATH}:./lib/cgejb_client.jar"
# CLASSPATH="${CLASSPATH}:./lib/CGWebService.jar"
CLASSPATH="${CLASSPATH}:./lib/CSTRWebService.jar"
CLASSPATH="${CLASSPATH}:./lib/commons-beanutils.jar"
CLASSPATH="${CLASSPATH}:./lib/commons-collections.jar"
CLASSPATH="${CLASSPATH}:./lib/commons-digester-1.7.jar"
CLASSPATH="${CLASSPATH}:./lib/commons-logging.jar"
CLASSPATH="${CLASSPATH}:./lib/com_gpki_sdk.jar"
# CLASSPATH="${CLASSPATH}:./lib/issacweb.jar"
CLASSPATH="${CLASSPATH}:./lib/jsr173_api.jar"
CLASSPATH="${CLASSPATH}:./lib/log4j-1.2.11.jar"
CLASSPATH="${CLASSPATH}:./lib/mail.jar"
CLASSPATH="${CLASSPATH}:./lib/quartz.jar"
CLASSPATH="${CLASSPATH}:./lib/schemas.jar"
CLASSPATH="${CLASSPATH}:./lib/schemas.v.0.89.jar"
CLASSPATH="${CLASSPATH}:./lib/webserviceclient.jar"
# CLASSPATH="${CLASSPATH}:./lib/weblogic.jar"
CLASSPATH="${CLASSPATH}:./lib/xbean-2.2.0.jar"
CLASSPATH="${CLASSPATH}:./lib/xbean_xpath.jar"
CLASSPATH="${CLASSPATH}:./lib/ctrutil.jar"
CLASSPATH="${CLASSPATH}:./lib/libgpkiapi_jni.jar"
CLASSPATH="${CLASSPATH}:./lib/xmlsec-1.3.0.jar"
CLASSPATH="${CLASSPATH}:./lib/commons-codec-1.6.jar"
CLASSPATH="${CLASSPATH}:./lib/StrSchemas.jar"
CLASSPATH="${CLASSPATH}:./lib/ldapjdk.jar"
CLASSPATH="${CLASSPATH}:./lib/jxl.jar"

# add wmq_lib
CLASSPATH="${CLASSPATH}:./lib/wmqlib/com.ibm.mq.pcf.jar"
CLASSPATH="${CLASSPATH}:./lib/wmqlib/com.ibm.mqjms.jar"
CLASSPATH="${CLASSPATH}:./lib/wmqlib/mqcontext.jar"

# add ctrutil lib path
#CLASSPATH="${CLASSPATH}:./lib/javax.jms-1.1.jar"
CLASSPATH="${CLASSPATH}:./lib/ldapjdk.jar"
CLASSPATH="${CLASSPATH}:./lib/sggpki.jar"
CLASSPATH="${CLASSPATH}:./lib/sgsecukit.jar"
CLASSPATH="${CLASSPATH}:./lib/sgkm.jar"
CLASSPATH="${CLASSPATH}:./lib/signgate_common.jar"
CLASSPATH="${CLASSPATH}:./lib/signgateCrypto.jar"
